name: Build and Deploy SvelteKit (Node Adapter) to FTP

on:
  push:
    branches: [main] # Trigger the action on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your preferred Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create app.cjs
        run: |
          cat << EOF > build/app.cjs
          // Your custom app.cjs code here
          async function loadApp() {
              await import("./index.js");
              }
          loadApp();
          EOF

      - name: Prepare for deployment
        run: |
          mkdir deploy
          cp -r build package.json package-lock.json deploy/
          cd deploy && npm ci --production

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/ # Deploy the prepared directory
          server-dir: / # Adjust this to your server path
